# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pomocni1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600) #*********************************
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.checkBoxEnkripcija = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxEnkripcija.setGeometry(QtCore.QRect(40, 480, 91, 20))
        self.checkBoxEnkripcija.setObjectName("checkBoxEnkripcija")

        self.checkBoxPotpis = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxPotpis.setGeometry(QtCore.QRect(150, 480, 81, 20))
        self.checkBoxPotpis.setObjectName("checkBoxPotpis")

        self.checkBoxKompresija = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxKompresija.setGeometry(QtCore.QRect(240, 480, 101, 20))
        self.checkBoxKompresija.setObjectName("checkBoxKompresija")

        self.checkBoxRadix64 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxRadix64.setGeometry(QtCore.QRect(350, 480, 81, 20))
        self.checkBoxRadix64.setObjectName("checkBoxRadix64")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBoxEnkripcija.setText(_translate("MainWindow", "enrpicija"))
        self.checkBoxPotpis.setText(_translate("MainWindow", "potpis"))
        self.checkBoxKompresija.setText(_translate("MainWindow", "kompresija"))
        self.checkBoxRadix64.setText(_translate("MainWindow", "radix-64"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
