# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PRaChoice.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
from main import triple_des_encrypt, triple_des_decrypt
from SendMessage import Ui_send_message_window
from ReceiveMessage import Ui_receive_message_window

class Ui_PRa_choice_window(object):
    def setupUi(self, PRa_choice_window,parent=None):
        self.parent = parent
        self.Ui_PRa_choice_window = PRa_choice_window

        # GENERALNA PODESAVANJA PROZORA
        PRa_choice_window.setObjectName("PRa_choice_window")
        PRa_choice_window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(PRa_choice_window)
        self.centralwidget.setObjectName("centralwidget")

        # PODESAVANJA TABELE
        self.PRa_table = QtWidgets.QTableWidget(self.centralwidget)
        self.PRa_table.setGeometry(QtCore.QRect(50, 20, 600, 300))
        self.PRa_table.setObjectName("PRa_table")
        self.PRa_table.setColumnCount(2)
        self.PRa_table.setRowCount(0)

        # PODESAVANJA POLJA TABELE
        #podesavanje hedera i izgleda
        self.PRa_table.setHorizontalHeaderLabels(('KEY ID', 'PRIVATE KEY'))
        self.PRa_table.setColumnWidth(0, 300)
        self.PRa_table.setColumnWidth(1, 300)

        # generisanje polja
        self.generate_table_PRa()

        # SUBMIT PRa BTN - VISAK
        # self.submit_PRa_btn = QtWidgets.QPushButton(self.centralwidget)
        # self.submit_PRa_btn.setGeometry(QtCore.QRect(470, 400, 181, 51))
        # self.submit_PRa_btn.setObjectName("submit_PRa_btn")

        # DODATNA PODESAVANJA PROZORA
        PRa_choice_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PRa_choice_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        PRa_choice_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PRa_choice_window)
        self.statusbar.setObjectName("statusbar")
        PRa_choice_window.setStatusBar(self.statusbar)


        self.retranslateUi(PRa_choice_window)
        QtCore.QMetaObject.connectSlotsByName(PRa_choice_window)

        # --> PODESAVANJE FUNKCIONALNOSTI

        self.generate_table_PRa()
        self.PRa_table.cellClicked.connect(self.cell_was_clicked)


    def generate_table_PRa(self):

        directory = "private_keys"
        pr_files = os.listdir(directory) # vraca imena
        pr_files_txt = [f for f in pr_files if (os.path.isfile(os.path.join(directory, f)) and f.endswith('.txt'))]

        self.all_pr_info = []

        i = 0
        for f in pr_files_txt:
            f_path = "private_keys/" + f
            with open(f_path, 'r') as file:
                for line in file:
                    line_arr = line.split(' admin ')
                    all_pr_info_el = [line_arr[0], line_arr[2]]
                    self.all_pr_info.append(all_pr_info_el)
                    i += 1
            file.close()

        num_of_rows = i
        num_of_cols = 2
        self.PRa_table.setRowCount(num_of_rows)

        for i in range(0, num_of_rows):
            for j in range(0, num_of_cols):
                item = self.all_pr_info[i][j]
                self.PRa_table.setItem(i, j, QtWidgets.QTableWidgetItem(item))
                self.PRa_table.resizeRowsToContents()
                self.PRa_table.resizeColumnsToContents()

    def open_password_auth_window(self, key_id_arg):
        from PasswordAuth import Ui_password_auth_window
        self.password_auth_window = QtWidgets.QMainWindow()
        self.ui = Ui_password_auth_window()
        self.ui.setupUi(self.password_auth_window, key_id_arg,parent=self.Ui_PRa_choice_window)
        self.password_auth_window.show()

    def cell_was_clicked(self, row, column):
        if (column == 0):
            cell = self.PRa_table.item(row, column)
            cell_contents = cell.text()
            Ui_send_message_window.temp_key_id_for_PRa = int(cell_contents)
            Ui_receive_message_window.temp_key_id_for_PRb=int(cell_contents)
            print("temp_key_id_for_PRa: " + cell_contents)

            self.open_password_auth_window(int(cell_contents))




    def retranslateUi(self, PRa_choice_window):
        _translate = QtCore.QCoreApplication.translate
        PRa_choice_window.setWindowTitle(_translate("PRa_choice_window", "PRa_choice_window"))
        #self.submit_PRa_btn.setText(_translate("PRa_choice_window", "Choose"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PRa_choice_window = QtWidgets.QMainWindow()
    ui = Ui_PRa_choice_window()
    ui.setupUi(PRa_choice_window)
    PRa_choice_window.show()
    sys.exit(app.exec_())
