
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Aug 26 12:17:52 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATERTHAN = 33;
  public static final int INCREMENT = 29;
  public static final int GREATERTHANOREQUAL = 34;
  public static final int CONST = 7;
  public static final int EQUALS = 31;
  public static final int NAMESPACE = 9;
  public static final int SLASH = 25;
  public static final int LESSTHANOREQUAL = 36;
  public static final int BITWISEAND = 27;
  public static final int LPAREN = 17;
  public static final int SEMI = 13;
  public static final int MINUS = 23;
  public static final int DECREMENT = 30;
  public static final int CHARACTER = 40;
  public static final int RPAREN = 18;
  public static final int LSQUAREBRACKET = 19;
  public static final int LESSTHAN = 35;
  public static final int COMMA = 12;
  public static final int BITWISEOR = 28;
  public static final int PLUS = 22;
  public static final int IF = 10;
  public static final int BOOLEAN = 39;
  public static final int EOF = 0;
  public static final int RETURN = 3;
  public static final int EQUAL = 21;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int PERCENT = 26;
  public static final int NUMBER = 38;
  public static final int IDENT = 37;
  public static final int VOID = 6;
  public static final int TIMES = 24;
  public static final int RSQUAREBRACKET = 20;
  public static final int COLON = 14;
  public static final int LBRACE = 15;
  public static final int ELSE = 11;
  public static final int READ = 5;
  public static final int DIFFERS = 32;
  public static final int RBRACE = 16;
  public static final int PROG = 2;
  public static final int PRINT = 4;
}

